name: SIGE Web - CI/PRD

on:
  push:
    branches:
      - main
    paths:
      - 'web/**'
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Check if index.html exists
      working-directory: /var/www
      run: if [ ! -f index.html ]; then echo "File does not exist"; exit 1; fi
    
    - name: Copy index.html
      working-directory: /var/www
      run: cp index.html /var/www/prd/web/index.html
        
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Install dependencies
      working-directory: web
      run: npm install --legacy-peer-deps

    - name: Set environment variables
      run: |
        echo "BASE_API_URL=${{ vars.BASE_API_URL }}" >> $GITHUB_ENV
        
    - name: Replace variables in environment.prod.ts
      working-directory: web/src/environments
      run: |
        # Usando envsubst para substituir todas as variáveis no arquivo environment.prod.ts
        envsubst < environment.prod.ts > environment.prod.temp.ts
        mv environment.prod.temp.ts environment.prod.ts
        
    - name: Build the project
      working-directory: web
      run: npm run build -- --configuration=production

    - name: Deploy to VPS
      env:
        HOST: ${{ vars.VPS_HOST }}
        USERNAME: ${{ vars.VPS_USERNAME }}
        PASSWORD: ${{ secrets.VPS_PASSWORD }}
      run: |
        sshpass -p "$PASSWORD" ssh -o StrictHostKeyChecking=no $USERNAME@$HOST "rm -rf /var/www/prd/web/*"
        sshpass -p "$PASSWORD" scp -r web/dist/* $USERNAME@$HOST:/var/www/prd/web/
