name: Database Restore PRD

on:
  workflow_dispatch:

jobs:
  dump-and-restore:
    runs-on: ubuntu-latest
    env:
        VPS_USERNAME: ${{ vars.VPS_USERNAME }}
        VPS_HOST: ${{ vars.VPS_HOST }}
        VPS_PASSWORD: ${{ secrets.VPS_PASSWORD }}
        DB_HOST_PRD: ${{ vars.DB_HOST }}
        DB_USER_PRD: ${{ vars.DB_USER_PRD }}
        DB_PASS_PRD: ${{ secrets.DB_PASS_PRD }}
        DB_HOST_OLD: ${{ vars.DB_HOST_OLD }}
        DB_USER_OLD: ${{ vars.DB_USER_OLD }}
        DB_PASS_OLD: ${{ secrets.DB_PASS_OLD }}
    steps:      
      - name: Set up MySQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client
      - name: Dump coenel-old database
        run: |
          mysqldump --no-tablespaces -h $DB_HOST_OLD -u $DB_USER_OLD -p$DB_PASS_OLD coenel > dump_coenel_old.sql
      - name: Upload dump to VPS
        run: |
          sshpass -p "$VPS_PASSWORD" scp -o StrictHostKeyChecking=no dump_coenel_old.sql $VPS_USERNAME@$VPS_HOST:/tmp/dump_coenel_old.sql
      - name: Restore dump to coenel-prd
        run: |
          sshpass -p "$VPS_PASSWORD" ssh -o StrictHostKeyChecking=no $VPS_USERNAME@$VPS_HOST \
          "mysql -h '$DB_HOST_PRD' -u '$DB_USER_PRD' -p'$DB_PASS_PRD' --default-character-set=utf8mb4 coenel-prd < /tmp/dump_coenel_old.sql"
      
      - name: Clean up
        run: |
          rm dump_coenel_old.sql
          sshpass -p "$VPS_PASSWORD" ssh -o StrictHostKeyChecking=no $VPS_USERNAME@$VPS_HOST "rm /tmp/dump_coenel_old.sql"
