import { Component } from "@angular/core";
import { RelatorioEconomiaPdfService } from "./relatorio-economia-pdf.service";
import { AlertService } from "../../../@core/services/util/alert.service";
import { IRelatorioEconomia } from "../../../@core/data/relatorio-economia";

@Component({
  selector: "ngx-relatorio-economia",
  templateUrl: "./relatorio-economia.component.html",
  styleUrls: ["./relatorio-economia.component.scss"],
})
export class RelatorioEconomiaComponent {
  constructor(
    private relatorioEconomiaPdfService: RelatorioEconomiaPdfService,
    private alertService: AlertService
  ) {}

  public downloadAsPdf(): void {
    this.alertService.showWarning(
      "Iniciando a geração e download do relatório de economia em PDF.",
      120
    );
    this.relatorioEconomiaPdfService.downloadPDF(response);
  }
}

const response: IRelatorioEconomia = {
  success: true,
  status: 200,
  data: {
    cabecalho: {
      titulo: "QUADRO COMPARATIVO MENSAL MERCADO CATIVO X LIVRE",
      subTitulo: "ROTA INDÚSTRIA GRÁFICA LTDA",
      unidade: "Estrela",
      subMercado: "Sul",
      conexao: "A4",
      concessao: "RGE Sul",
      dataAnalise: "2025-04-29T14:24:03",
      mesReferencia: "Outubro/24",
      numerorDiasMes: 31,
      periodoHoroSazonal: "Bandeira Verde",
    },
    grupos: [
      {
        ordem: 0,
        titulo: "MERCADO CATIVO - A4 - TOTAL",
        colunaQuantidade: "Montante",
        colunaValor: "Tarifa",
        colunaTotal: "Total",
        subGrupos: [
          {
            lancamentos: [
              {
                ordem: 0,
                descricao: "Demanda Contratada - Ponta",
                observacao:
                  "Tarifa Fornecimento - Resolução ANEEL nº 3.206, 13/06/2023",
                tipoLancamento: 0,
                subTotalizador: false,
                totalizador: false,
              },
              {
                ordem: 0,
                descricao: "Demanda Contratada - Fora de Ponta",
                montante: 500,
                tipoMontante: 1,
                tarifa: 40,
                tipoTarifa: 1,
                total: 20000,
                tipoLancamento: 0,
                subTotalizador: false,
                totalizador: false,
              },
              {
                ordem: 0,
                descricao: "Demanda Faturada - Ponta",
                tipoLancamento: 0,
                subTotalizador: false,
                totalizador: false,
              },
              {
                ordem: 0,
                descricao: "Demanda Faturada - Fora de Ponta",
                montante: 484,
                tipoMontante: 1,
                tarifa: 32.70933401,
                tipoTarifa: 1,
                total: 15831.317660839999,
                tipoLancamento: 0,
                subTotalizador: false,
                totalizador: false,
              },
              {
                ordem: 0,
                descricao: "Demanda Faturada - Fora de Ponta",
                montante: 16,
                tipoMontante: 1,
                tarifa: 27.14874722,
                tipoTarifa: 1,
                total: 434.37995552,
                tipoLancamento: 0,
                subTotalizador: false,
                totalizador: false,
              },
              {
                ordem: 0,
                descricao: "Demanda Ultrapassagem - Fora de Ponta",
                tarifa: 65.41866801,
                tipoTarifa: 1,
                tipoLancamento: 0,
                subTotalizador: false,
                totalizador: false,
              },
              {
                ordem: 0,
                descricao: "Demanda Reativa - Ponta",
                tipoLancamento: 0,
                subTotalizador: false,
                totalizador: false,
              },
              {
                ordem: 0,
                descricao: "Demanda Reativa - Fora de Ponta",
                tipoLancamento: 0,
                subTotalizador: false,
                totalizador: false,
              },
              {
                ordem: 0,
                descricao: "Consumo Medido - Ponta - TUSD",
                montante: 9476,
                tipoMontante: 1,
                tarifa: 2.04303417,
                tipoTarifa: 2,
                total: 19359.79179492,
                tipoLancamento: 0,
                subTotalizador: false,
                totalizador: false,
              },
              {
                ordem: 0,
                descricao: "Consumo Medido - Fora de Ponta - TUSD",
                montante: 75316,
                tipoMontante: 1,
                tarifa: 0.11999791,
                tipoTarifa: 2,
                total: 9037.76258956,
                tipoLancamento: 0,
                subTotalizador: false,
                totalizador: false,
              },
              {
                ordem: 0,
                descricao: "Consumo Medido - Ponta - TE",
                montante: 9476,
                tipoMontante: 1,
                tarifa: 0.49644406,
                tipoTarifa: 2,
                total: 4704.30391256,
                tipoLancamento: 0,
                subTotalizador: false,
                totalizador: false,
              },
              {
                ordem: 0,
                descricao: "Consumo Medido - Fora de Ponta - TE",
                montante: 75316,
                tipoMontante: 1,
                tarifa: 0.3148068,
                tipoTarifa: 2,
                total: 23709.9889488,
                tipoLancamento: 0,
                subTotalizador: false,
                totalizador: false,
              },
              {
                ordem: 0,
                descricao: "Adicional Bandeira Verde Ponta",
                tipoLancamento: 0,
                subTotalizador: false,
                totalizador: false,
              },
              {
                ordem: 0,
                descricao: "Adicional Bandeira Verde F. Ponta",
                tipoLancamento: 0,
                subTotalizador: false,
                totalizador: false,
              },
              {
                ordem: 0,
                descricao: "Consumo Medido Reativo - Ponta",
                tarifa: 0.36667518,
                tipoTarifa: 1,
                tipoLancamento: 0,
                subTotalizador: false,
                totalizador: false,
              },
              {
                ordem: 0,
                descricao: "Consumo Medido Reativo - Fora de Ponta",
                montante: 60.228,
                tipoMontante: 1,
                tarifa: 0.36992761,
                tipoTarifa: 2,
                total: 22.280000095080002,
                tipoLancamento: 0,
                subTotalizador: false,
                totalizador: false,
              },
            ],
            total: {
              ordem: 0,
              descricao: "Total geral mercado cativo (impostos inclusos)",
              montante: 84792,
              tipoMontante: 2,
              tarifa: 0.8621,
              tipoTarifa: 2,
              total: 73099.1832,
              tipoLancamento: 0,
              subTotalizador: false,
              totalizador: false,
            },
          },
        ],
      },
      {
        ordem: 1,
        titulo: "MERCADO LIVRE - A4",
        colunaQuantidade: "Montante",
        colunaValor: "Tarifa",
        colunaTotal: "Total",
        subGrupos: [
          {
            lancamentos: [
              {
                ordem: 0,
                descricao: "Perdas Reais",
                montante: 3,
                tipoMontante: 3,
                tipoLancamento: 0,
                subTotalizador: false,
                totalizador: false,
              },
              {
                ordem: 0,
                descricao: "Consumo de Energia Considerando Perdas e PROINFA",
                montante: 87.346,
                tipoMontante: 0,
                tipoLancamento: 0,
                subTotalizador: false,
                totalizador: false,
              },
              {
                ordem: 0,
                descricao: "PROINFA",
                montante: 1.998,
                tipoMontante: 0,
                tipoLancamento: 0,
                subTotalizador: false,
                totalizador: false,
              },
              {
                ordem: 0,
                descricao: "Consumo de Energia - Longo Prazo",
                montante: 80.287,
                tipoMontante: 0,
                tarifa: 282.94,
                tipoTarifa: 0,
                total: 22716.40378,
                tipoLancamento: 0,
                subTotalizador: false,
                totalizador: false,
              },
              {
                ordem: 0,
                descricao: "Consumo de Energia - Curto Prazo",
                montante: 5.061,
                tipoMontante: 0,
                tarifa: 132.59,
                tipoTarifa: 0,
                total: 671.03799,
                tipoLancamento: 0,
                subTotalizador: false,
                totalizador: false,
              },
              {
                ordem: 0,
                descricao: "Sub-total de compra de energia elétrica",
                total: 28177.64,
                tipoLancamento: 0,
                subTotalizador: false,
                totalizador: true,
              },
              {
                ordem: 0,
                descricao: "TUSD-Verde = 50,00% TUSD - Ponta",
                tipoLancamento: 0,
                subTotalizador: false,
                totalizador: false,
              },
              {
                ordem: 0,
                descricao: "TUSD - Fora de Ponta",
                montante: 484,
                tipoMontante: 1,
                tarifa: 16.42147803,
                tipoTarifa: 1,
                total: 7947.99536652,
                tipoLancamento: 0,
                subTotalizador: false,
                totalizador: false,
              },
              {
                ordem: 0,
                descricao: "TUSD - Fora de Ponta",
                montante: 16,
                tipoMontante: 1,
                tarifa: 13.62867111,
                tipoTarifa: 1,
                total: 218.05873776,
                tipoLancamento: 0,
                subTotalizador: false,
                totalizador: false,
              },
              {
                ordem: 0,
                descricao: "TUSD Ultrapassagem- Fora de Ponta",
                tipoLancamento: 0,
                subTotalizador: false,
                totalizador: false,
              },
              {
                ordem: 0,
                descricao: "Demanda Reativa - Ponta",
                tipoLancamento: 0,
                subTotalizador: false,
                totalizador: false,
              },
              {
                ordem: 0,
                descricao: "Demanda Reativa - Fora de Ponta",
                tipoLancamento: 0,
                subTotalizador: false,
                totalizador: false,
              },
              {
                ordem: 0,
                descricao: "TUSD Encargos - Ponta",
                montante: 9476,
                tipoMontante: 1,
                tarifa: 1.08544402,
                tipoTarifa: 2,
                total: 10285.66753352,
                tipoLancamento: 0,
                subTotalizador: false,
                totalizador: false,
              },
              {
                ordem: 0,
                descricao: "TUSD Encargos - Fora de Ponta",
                montante: 75316,
                tipoMontante: 1,
                tarifa: 0.11999791,
                tipoTarifa: 2,
                total: 9037.76258956,
                tipoLancamento: 0,
                subTotalizador: false,
                totalizador: false,
              },
              {
                ordem: 0,
                descricao: "Consumo Reativo - Ponta",
                tarifa: 0.36667518,
                tipoTarifa: 2,
                tipoLancamento: 0,
                subTotalizador: false,
                totalizador: false,
              },
              {
                ordem: 0,
                descricao: "Consumo Reativo - Fora de Ponta",
                montante: 60.228,
                tipoMontante: 1,
                tarifa: 0.36992761,
                tipoTarifa: 2,
                total: 22.280000095080002,
                tipoLancamento: 0,
                subTotalizador: false,
                totalizador: false,
              },
              {
                ordem: 0,
                descricao: "Subvenção Tarifária - TUSD - Com ICMS DEZ/23",
                total: 16957.42,
                tipoLancamento: 0,
                subTotalizador: true,
                totalizador: false,
              },
              {
                ordem: 0,
                descricao: "Subvenção Tarifária - TUSD - Sem ICMS DEZ/23",
                total: 216.31,
                tipoLancamento: 0,
                subTotalizador: true,
                totalizador: false,
              },
              {
                ordem: 0,
                descricao:
                  "Sub-total para base de cálculo imposto ICMS/PIS/COFINS",
                total: 44685.51,
                tipoLancamento: 0,
                subTotalizador: false,
                totalizador: true,
              },
              {
                ordem: 0,
                descricao: "Ajustes da TUSD",
                total: 36.85,
                tipoLancamento: 0,
                subTotalizador: true,
                totalizador: false,
              },
              {
                ordem: 0,
                descricao: "Credito Subv. Tarifa ACL Tusd",
                total: -13517.83,
                tipoLancamento: 0,
                subTotalizador: true,
                totalizador: false,
              },
              {
                ordem: 0,
                descricao: "Total distribuidora",
                total: 31204.53,
                tipoLancamento: 0,
                subTotalizador: false,
                totalizador: true,
              },
              {
                ordem: 0,
                descricao: "Ressarcimento",
                tipoLancamento: 0,
                subTotalizador: true,
                totalizador: false,
              },
              {
                ordem: 0,
                descricao: "Multa",
                tipoLancamento: 0,
                subTotalizador: true,
                totalizador: false,
              },
              {
                ordem: 0,
                descricao: "Juros",
                tipoLancamento: 0,
                subTotalizador: true,
                totalizador: false,
              },
              {
                ordem: 0,
                descricao: "Sub-total de valores referente a Distribuidora",
                total: 31273.79,
                tipoLancamento: 0,
                subTotalizador: false,
                totalizador: true,
              },
              {
                ordem: 0,
                descricao:
                  "Serviço Depositário Qualificado - Bradesco Ref.: 12/23",
                total: 42.24,
                tipoLancamento: 0,
                subTotalizador: true,
                totalizador: false,
              },
              {
                ordem: 0,
                descricao: "EER - Energia de Reserva - 11/23",
                total: 1741.31,
                tipoLancamento: 0,
                subTotalizador: true,
                totalizador: false,
              },
              {
                ordem: 0,
                descricao:
                  "Contribuição Associativa mensal CCEE - 12/23- Vcto. 29.12.23",
                total: 63.13,
                tipoLancamento: 0,
                subTotalizador: true,
                totalizador: false,
              },
              {
                ordem: 0,
                descricao:
                  "Liq. Fin. CCEE - DEVEDOR/CREDOR (ref. 10/23) Vcto.: 11.12.23",
                total: 174.27,
                tipoLancamento: 0,
                subTotalizador: true,
                totalizador: false,
              },
              {
                ordem: 0,
                descricao: "Sub-total dos outros custos mercado livre",
                total: 2020.95,
                tipoLancamento: 0,
                subTotalizador: false,
                totalizador: true,
              },
            ],
            total: {
              ordem: 0,
              descricao: "Total geral mercado cativo (impostos inclusos)",
              tarifa: 0.7242,
              tipoTarifa: 2,
              total: 61403.12,
              tipoLancamento: 0,
              subTotalizador: false,
              totalizador: false,
            },
          },
        ],
      },
    ],
  },
  message: "",
  errors: [],
};
